/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed": "#0f0069",
        "inverse-primary": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "secondary": "#006c49",
        "surface-container-low": "#f5f2ff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffd2be",
        "primary-fixed-dim": "#c3c0ff",
        "on-background": "#1b1b24",
        "tertiary-container": "#a44100",
        "background": "#fcf8ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbcc",
        "surface-variant": "#e4e1ee",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#005236",
        "outline-variant": "#c7c4d8",
        "tertiary-fixed-dim": "#ffb695",
        "secondary-fixed": "#6ffbbe",
        "inverse-on-surface": "#f3effc",
        "on-tertiary-fixed": "#351000",
        "on-primary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-surface": "#1b1b24",
        "on-primary-container": "#dad7ff",
        "surface-container-highest": "#e4e1ee",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-error-container": "#93000a",
        "primary-container": "#4f46e5",
        "surface-container": "#f0ecf9",
        "tertiary": "#7e3000",
        "on-secondary-fixed": "#002113",
        "on-surface-variant": "#464555",
        "surface-dim": "#dcd8e5",
        "inverse-surface": "#302f39",
        "outline": "#777587",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-container": "#00714d",
        "surface-container-lowest": "#ffffff",
        "primary": "#3525cd",
        "surface-bright": "#fcf8ff",
        "surface-container-high": "#eae6f4",
        "surface": "#fcf8ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "16px",
        "2xl": "48px",
        "unit": "4px",
        "xs": "4px",
        "gutter": "20px",
        "margin": "32px",
        "lg": "24px",
        "xl": "32px",
        "sm": "8px"
      },
      "fontFamily": {
        "body-md": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "button": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "h1": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["13px", {"lineHeight": "16px", "fontWeight": "500"}],
        "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}],
        "h3": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
